#! /bin/bash

portnum=12345

check=$(nmap -A 192.168.1.194 -p "$portnum" | grep tcp | cut -d' ' -f2)
if [[ "$check" = "open" ]]
	then
		echo "$portnum is open!"
	else
		echo "$portnum is closed!"
fi

